name: resume-screener
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - boto3
  - python-dotenv
  - pip
  - pip:
      - sentence-transformers
      - fastapi
      - uvicorn
      - python-multipart
      - jinja2
      - pdfminer.six